// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: common/v1/common.proto

package common

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/protobuf/types/descriptorpb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type RespCode int32

const (
	RespCode_OK        RespCode = 0
	RespCode_FAIL      RespCode = 1
	RespCode_PARAM_ERR RespCode = 2
)

var RespCode_name = map[int32]string{
	0: "OK",
	1: "FAIL",
	2: "PARAM_ERR",
}

var RespCode_value = map[string]int32{
	"OK":        0,
	"FAIL":      1,
	"PARAM_ERR": 2,
}

func (x RespCode) String() string {
	return proto.EnumName(RespCode_name, int32(x))
}

func (RespCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_92d5df4519b8f2e3, []int{0}
}

type RespObj struct {
	// @gotags: json:"Code"
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *AnyObj  `protobuf:"bytes,3,opt,name=Data,proto3,customtype=AnyObj" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespObj) Reset()         { *m = RespObj{} }
func (m *RespObj) String() string { return proto.CompactTextString(m) }
func (*RespObj) ProtoMessage()    {}
func (*RespObj) Descriptor() ([]byte, []int) {
	return fileDescriptor_92d5df4519b8f2e3, []int{0}
}
func (m *RespObj) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespObj.Unmarshal(m, b)
}
func (m *RespObj) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespObj.Marshal(b, m, deterministic)
}
func (m *RespObj) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespObj.Merge(m, src)
}
func (m *RespObj) XXX_Size() int {
	return xxx_messageInfo_RespObj.Size(m)
}
func (m *RespObj) XXX_DiscardUnknown() {
	xxx_messageInfo_RespObj.DiscardUnknown(m)
}

var xxx_messageInfo_RespObj proto.InternalMessageInfo

func (m *RespObj) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RespObj) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Any struct {
	Data                 *AnyObj  `protobuf:"bytes,1,opt,name=Data,proto3,customtype=AnyObj" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Any) Reset()         { *m = Any{} }
func (m *Any) String() string { return proto.CompactTextString(m) }
func (*Any) ProtoMessage()    {}
func (*Any) Descriptor() ([]byte, []int) {
	return fileDescriptor_92d5df4519b8f2e3, []int{1}
}
func (m *Any) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Any.Unmarshal(m, b)
}
func (m *Any) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Any.Marshal(b, m, deterministic)
}
func (m *Any) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Any.Merge(m, src)
}
func (m *Any) XXX_Size() int {
	return xxx_messageInfo_Any.Size(m)
}
func (m *Any) XXX_DiscardUnknown() {
	xxx_messageInfo_Any.DiscardUnknown(m)
}

var xxx_messageInfo_Any proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("api.common.v1.RespCode", RespCode_name, RespCode_value)
	proto.RegisterType((*RespObj)(nil), "api.common.v1.RespObj")
	proto.RegisterType((*Any)(nil), "api.common.v1.Any")
}

func init() { proto.RegisterFile("common/v1/common.proto", fileDescriptor_92d5df4519b8f2e3) }

var fileDescriptor_92d5df4519b8f2e3 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcf, 0x4b, 0xc3, 0x30,
	0x1c, 0xc5, 0xcd, 0x56, 0xbb, 0xed, 0x8b, 0x83, 0x92, 0x83, 0x94, 0x81, 0x5a, 0x06, 0x42, 0x51,
	0xb6, 0x6c, 0x78, 0x14, 0xc4, 0xce, 0x1f, 0x20, 0x2a, 0x95, 0x5c, 0x04, 0x2f, 0x92, 0x76, 0x31,
	0x66, 0xb4, 0x4d, 0x68, 0xbb, 0xb1, 0xfd, 0xab, 0x1e, 0xfc, 0x5b, 0xa4, 0x89, 0xf6, 0xe4, 0xed,
	0xf3, 0x7d, 0xef, 0x85, 0x47, 0x1e, 0x1c, 0xa6, 0x2a, 0xcf, 0x55, 0x41, 0x36, 0x73, 0x62, 0x69,
	0xaa, 0x4b, 0x55, 0x2b, 0x3c, 0x64, 0x5a, 0x4e, 0x7f, 0x95, 0xcd, 0x7c, 0x14, 0x08, 0xa5, 0x44,
	0xc6, 0x89, 0x31, 0x93, 0xf5, 0x07, 0x59, 0xf2, 0x2a, 0x2d, 0xa5, 0xae, 0x55, 0x69, 0x1f, 0x8c,
	0x8e, 0x5a, 0x4b, 0x28, 0xa1, 0xcc, 0x61, 0xc8, 0xda, 0xe3, 0x57, 0xe8, 0x51, 0x5e, 0xe9, 0x38,
	0x59, 0x61, 0x0c, 0x4e, 0xaa, 0x96, 0xdc, 0x47, 0x01, 0x0a, 0xf7, 0xa9, 0x61, 0xec, 0x43, 0x2f,
	0xe7, 0x55, 0xc5, 0x04, 0xf7, 0x3b, 0x01, 0x0a, 0x07, 0xf4, 0xef, 0xc4, 0xc7, 0xe0, 0xdc, 0xb2,
	0x9a, 0xf9, 0xdd, 0x00, 0x85, 0x07, 0x0b, 0xf8, 0xfa, 0x3e, 0x71, 0xa3, 0x62, 0x17, 0x27, 0x2b,
	0x6a, 0xf4, 0xf1, 0x29, 0x74, 0xa3, 0x62, 0xd7, 0xc6, 0xd0, 0xff, 0xb1, 0xb3, 0x73, 0xe8, 0x37,
	0xfd, 0x37, 0x4d, 0x99, 0x0b, 0x9d, 0xf8, 0xd1, 0xdb, 0xc3, 0x7d, 0x70, 0xee, 0xa3, 0x87, 0x27,
	0x0f, 0xe1, 0x21, 0x0c, 0x5e, 0x22, 0x1a, 0x3d, 0xbf, 0xdf, 0x51, 0xea, 0x75, 0x16, 0xd7, 0x6f,
	0x57, 0x42, 0xd6, 0x9f, 0xeb, 0xa4, 0x59, 0x80, 0x64, 0x5c, 0xb2, 0xed, 0x6c, 0x66, 0xff, 0x9e,
	0x4e, 0x04, 0x2f, 0x26, 0x42, 0x16, 0x84, 0x6f, 0x59, 0xae, 0x33, 0x4e, 0x98, 0x96, 0xa4, 0x1d,
	0xf1, 0xd2, 0x52, 0xe2, 0x9a, 0xf0, 0xc5, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x02, 0x95, 0xc0,
	0xb7, 0x5f, 0x01, 0x00, 0x00,
}
